### ISSUE TITLE
how to set the lamda?

### ISSUE THREAD

**Issue by ZZYhengiyou** [xuyxu/Deep-Clustering-Network#3]
Thank you very much for providing this version. But I am not able to get a result similar to the original or to your result when I run the program. I think it may be a problem with the definition of the hyperparameter lamda. Should lamda be the coefficient of the loss of autoencoder or the coefficient of kmeans?

**Comment by xuyxu** [comment]
Hi @ZZYhengiyou, I think adding lambda as a coefficient to the reconstruction term or the clustering term should be equivalent since we could specify its value when instantiating the DCN model.

For a model that reproduces the result, please refer to https://github.com/guenthereder/Deep-Clustering-Network, I did not spend much time on tuning parameters.

**Comment by ZZYhengiyou** [comment]
Ok, thanks for your enthusiastic answer, I will make finer adjustments the parameters. Thank you again!

**Comment by xuyxu** [comment]
Feel free to open another issue if you have any other problems.
